### ISSUE TITLE
error timeout app not restart

### ISSUE THREAD

**Issue by johnx102** [mangoose002/Meross2Domoticz#10]
Hi, thanks for you're work. 
i have a little problem so I don't find way to solve.
I launch the bridge with pm2 , but sometime program stop , but not crash so pm2 cannot restart it.
look like timeout problem, I show you the log .

0|meross2d | TypeError: Cannot read property 'ability' of undefined
0|meross2d |     at Object.dev.getSystemAbilities [as callback] (/home/pi/Meross2Domoticz/meross2domoticz.js:247:28)
0|meross2d |     at Timeout.waitingMessageIds.(anonymous function).timeout.setTimeout [as _onTimeout] (/home/pi/Meross2Domoticz/node_modules/meross-cloud/index.js:333:55)
0|meross2d |     at ontimeout (timers.js:475:11)
0|meross2d |     at tryOnTimeout (timers.js:310:5)
0|meross2d |     at Timer.listOnTimeout (timers.js:270:5)

Thanks for you're time , I hope you can help me.

**Comment by Mikado8231** [comment]
Hello,

I updated locally the delay of the timeout from 20000 to 40000 in the meross-cloud code.
https://github.com/Apollon77/meross-cloud/blob/c7cbd6be3333f3ad8e4ca218f8cd1a1b8a201b01/index.js#L337

For me, now it works correctly.
Regards
