### ISSUE TITLE
Syntaxe Error ...

### ISSUE THREAD

**Issue by Yosh76** [mangoose002/Meross2Domoticz#11]
Hello !

I have a problem...
Can you help me ?

My logs says : 

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/meross2domoticz.js:72:29)
    at Request.self.callback (/home/pi/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/pi/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/pi/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)

```
Thanks !

**Comment by Yosh76** [comment]
Solution trouvée.

Dans le config.json j'ai modifié localhost de mon domoticz par son ip ;)
