### ISSUE TITLE
Created but nothing works

### ISSUE THREAD

**Issue by macbenoit** [mangoose002/Meross2Domoticz#12]
Installed on a raspbian buster domoticz last update 
It has created my switches but it won’t work

**Comment by Latermocdelo** [comment]
I have the same issue.

**Comment by Eless54** [comment]
You need to link ur MQTT device to Domoticz and start with node or pm2 the meross2domoticz.js

**Comment by lolomin** [comment]
Same for me with a MSS310, virtual devices are created but after this nothing works, On/Off virtual switch has no effect on the device, Virtual consommation never updated, no logs excepted : "Updating power consumption" which is constantly displayed every XX seconds as configured in the config.json.

config.json below : 

# cat config.json
{
"meross": {
"email": "EMAIL@DOMAIN.TLD",
"password": "MyPasswordHere"
},
"domoticz": {
"server": "127.0.0.1",
"port": 8888
},
"mqtt": {
"server": "192.168.0.1",
"port": 1883,
"username": "meross",
"password": "mypassword"
},
"powerUpdate": 10
}

Does this script still works or no please ?

Regards,

lolo

**Comment by jult** [comment]
_"No setup needed. Everything is created by the script in Domoticz (if new devices is authorized)"_
Well sorry, but no, a setup *is* needed, I'm pretty savy, but I have no clue what to even do with any of the files provided. Created by what script? Where does one put that script? How does one run it?

**Comment by lolomin** [comment]
> _"No setup needed. Everything is created by the script in Domoticz (if new devices is authorized)"_ Well sorry, but no, a setup _is_ needed, I'm pretty savy, but I have no clue what to even do with any of the files provided. Created by what script? Where does one put that script? How does one run it?

Hi,

On my side, finally succeed to make this script working on domoticz but this is unstable : 
- sometimes the script got killed without any reason, by analyzing the logs I'm doubting about problems with timeouts that make the script crashed but not sure ...
- very often : the commands to get the outlet to get on/off timeout when trying to access the Merross Cloud so it does not work, need to make the action again ...
- pm2 usage is not working : script is not registered properly and does not get restarted automatically

by the way as you can see : no answer by the dev, this script seems to be development's dead ...

Tried to integrate my 6 outlets on Home Assassin and this was a lot better than in Domoticz : LAN integration with direct command to outlet without need to go out on Internet and so no shitty Merross Cloud, working immediatly.

My opinion is that it is now time to give up with this script and more globally with Domoticz ...

Laurent

**Comment by mangoose002** [comment]
> _"No setup needed. Everything is created by the script in Domoticz (if new devices is authorized)"_ Well sorry, but no, a setup _is_ needed, I'm pretty savy, but I have no clue what to even do with any of the files provided. Created by what script? Where does one put that script? How does one run it?

Hi jult,

Did you have a look at the following link: https://github.com/mangoose002/Meross2Domoticz/wiki/Installation
That shoud tell you what to install before using this 'script'.

Regards

**Comment by mangoose002** [comment]
> > _"No setup needed. Everything is created by the script in Domoticz (if new devices is authorized)"_ Well sorry, but no, a setup _is_ needed, I'm pretty savy, but I have no clue what to even do with any of the files provided. Created by what script? Where does one put that script? How does one run it?
> 
> Hi,
> 
> On my side, finally succeed to make this script working on domoticz but this is unstable :
> 
> * sometimes the script got killed without any reason, by analyzing the logs I'm doubting about problems with timeouts that make the script crashed but not sure ...
> * very often : the commands to get the outlet to get on/off timeout when trying to access the Merross Cloud so it does not work, need to make the action again ...
> * pm2 usage is not working : script is not registered properly and does not get restarted automatically
> 
> by the way as you can see : no answer by the dev, this script seems to be development's dead ...
> 
> Tried to integrate my 6 outlets on Home Assassin and this was a lot better than in Domoticz : LAN integration with direct command to outlet without need to go out on Internet and so no shitty Merross Cloud, working immediatly.
> 
> My opinion is that it is now time to give up with this script and more globally with Domoticz ...
> 
> Laurent

Hi Laurent,

I am using this every day and have no problem.
This is ran through PM2 and works 'almost' flawlessly.

There must be something wrong in your configuration, but it seems that you use homeassistant now, so that may not be relevant anymore.

Regards

**Comment by lminost** [comment]
> > > _"No setup needed. Everything is created by the script in Domoticz (if new devices is authorized)"_ Well sorry, but no, a setup _is_ needed, I'm pretty savy, but I have no clue what to even do with any of the files provided. Created by what script? Where does one put that script? How does one run it?
> > 
> > 
> > Hi,
> > On my side, finally succeed to make this script working on domoticz but this is unstable :
> > 
> > * sometimes the script got killed without any reason, by analyzing the logs I'm doubting about problems with timeouts that make the script crashed but not sure ...
> > * very often : the commands to get the outlet to get on/off timeout when trying to access the Merross Cloud so it does not work, need to make the action again ...
> > * pm2 usage is not working : script is not registered properly and does not get restarted automatically
> > 
> > by the way as you can see : no answer by the dev, this script seems to be development's dead ...
> > Tried to integrate my 6 outlets on Home Assassin and this was a lot better than in Domoticz : LAN integration with direct command to outlet without need to go out on Internet and so no shitty Merross Cloud, working immediatly.
> > My opinion is that it is now time to give up with this script and more globally with Domoticz ...
> > Laurent
> 
> Hi Laurent,
> 
> I am using this every day and have no problem. This is ran through PM2 and works 'almost' flawlessly.
> 
> There must be something wrong in your configuration, but it seems that you use homeassistant now, so that may not be relevant anymore.
> 
> Regards

Hi mangoose002,

Thanks for your answer and glad yo hear you here.
I hope that the dev of the script is succeeding to make its script working, it would be a problem otherwise :)

And yes you're right, now in the process to migrate all my domoticz stuff to Home Assistant but just to be totaly transparent, your script i still sitting in background here through pm2 and just checked the logs and still too often full of :

`Error: Timeout
    at Timeout._onTimeout (/opt/Meross2Domoticz/node_modules/meross-cloud/index.js:517:68)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Error: Timeout
    at Timeout._onTimeout (/opt/Meross2Domoticz/node_modules/meross-cloud/index.js:517:68)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Error: Timeout
    at Timeout._onTimeout (/opt/Meross2Domoticz/node_modules/meross-cloud/index.js:517:68)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Error: Timeout
    at Timeout._onTimeout (/opt/Meross2Domoticz/node_modules/meross-cloud/index.js:517:68)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)`

or : 

`2023-02-20T07:53:05.305Z -- DEV: 2104177366193290849948e1e96d0c6f closed: null
2023-02-20T07:53:05.305Z -- 2104172804866790849948e1e96d14bd closed: null
2023-02-20T07:53:05.305Z -- DEV: 2104172804866790849948e1e96d14bd closed: null
2023-02-20T07:53:09.872Z -- Updating power consumption
2023-02-20T07:53:10.305Z -- 2208123133314751080C48e1e9a3d4f8 reconnected
2023-02-20T07:53:10.306Z -- DEV: 2208123133314751080C48e1e9a3d4f8 reconnected
2023-02-20T07:53:10.306Z -- 2111299984529051808148e1e97e70fc reconnected
2023-02-20T07:53:10.306Z -- DEV: 2111299984529051808148e1e97e70fc reconnected`

and this clearly too many times on a day for me, which lead to the usage experience 24/7 described above, I think this is part of the 'works 'almost' flawlessly' ;)

So maybe this is some rate limiting on Merross's side but IMO this clearly also lights the fact that when LAN could be used it is far better than going externally on the Internet and then come back, I think this approach should be used here.

Regards,

Laurent

**Comment by mangoose002** [comment]
Timeout are now fixed for offline devices (just added a test on the device status).
That should work better right now.

-P-
