### ISSUE TITLE
Domoticz ne créé pas de device pour ma prise connectée

### ISSUE THREAD

**Issue by Fabien14000** [mangoose002/Meross2Domoticz#7]
Bonjour.

Tout d'abord merci pour ton script.
J'utilise Domoticz 4.11214 sur un raspberry.
J'ai des prises Meross mss310. J'essaie d'en ajouter une sous Domoticz pour tester.

J'ai suivi les étapes du guide d'installation : https://github.com/mangoose002/Meross2Domoticz/wiki/Installation

Mais en activant sous Domoticz la détection automatique avec le bouton "Autoriser pendant 5 minutes", je n'obtiens rien, pas de dispositifs ajoutés.
J'ai beau jouer avec l'application Meross (allumer ou éteindre la prise), rien ne se passe dans domoticz.

Y'a-t-il un log que je peux consulter ? J'ai regardé dans /tmp/domoticz.log mais il n'y a rien.

Merci
Fabien

**Comment by Steshen** [comment]
Hello,

You can find the logs here  : 
-rw-r--r-- 1 pi pi       0 May 10 20:08 meross2domoticz-out.log
-rw-r--r-- 1 pi pi 2202160 May 11 11:53 meross2domoticz-error.log
pi@raspberrypi:~/.pm2/logs $ pwd
**/home/pi/.pm2/logs**

I've the same issue and here is my error log : 

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/installation/meross/meross2domoticz.js:72:29)
    at Request.self.callback (/home/pi/installation/meross/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/pi/installation/meross/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/pi/installation/meross/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)

Thanks in advance,
Steve

**Comment by mangoose002** [comment]
I added a new piece of code for this, and I will push it soon (normaly today).

**Comment by mangoose002** [comment]
The code was pushed today.
It should prevent from this error.
